### ISSUE TITLE
Cant find in nc appstore

### ISSUE THREAD

**Issue by Teyro** [icewind1991/files_external_dropbox#2] opened 2017-10-06 16:40 UTC
Hi thank for your work....

Cant use the Addon because it isnt in the app store :(

**Comment by Teyro** [comment] 2017-10-06 20:08
Cant compile it against php56 (uberspace.de german Nerd vserver Provider)..... Die someone get it to work?

**Comment by notjoe** [comment] 2017-10-06 21:04
Did you try using the Makefile provided?

**Comment by MariusBluem** [comment] 2017-10-08 13:23
Will be released as soon as it is tested and works as expexted.

**Comment by e-alfred** [comment] 2017-10-09 12:00
How do you solve the license problem?

**Comment by icewind1991** [comment] 2017-10-09 12:11
The license is now AGPLv3, the oC version changed it license a few times between gpl and agpl so I changed the port to be based on the most recent commit of them that was agpl licensed.

**Closed by icewind1991** 2017-10-09 12:11 UTC

**Comment by joekerna** [comment] 2017-10-12 17:58
But it's still not in the app store, is it?

**Comment by jgoerzen** [comment] 2017-10-16 12:34
I don't see it there either.  It seems this bug is not really closed, since README.md is pointing to something that doesn't exist.

**Comment by joekerna** [comment] 2017-12-05 09:01
Why is this closed? Is there any news on the app-store release?

**Comment by My1** [comment] 2018-02-11 11:05
I totally have to agree, this would be totally useful in the app store.

**Comment by af9** [comment] 2018-05-05 09:55
Is there any reason why it is still not released in app store? @MariusBluem mentioned it will be release as soon as tested... In [Nextcloud forum](https://help.nextcloud.com/t/nextcloud-12-cant-connect-dropbox/29425/4) someone confirmed its working... So what is problem? Maybe someone could support???

Not everybody want or is able to install it from sources... Especially I think the Nextcloud app manager will not be able to inform about available updates if this app was installed from sources. But it's not comfortable to manually check for updates on github. So I (and I guess not only me) really would appriciate if this app is available in app strore.

_**But**: I'm not complaining... :innocent: I really appreciate your work..._ :thumbsup:

**Comment by MariusBluem** [comment] 2018-05-05 14:03
As soon as it is tested and stable, this will be released by the maintainer (in this case @icewind1991) unrelated to whether this issue is open or closed.
