### ISSUE TITLE
Not in Apps?!?! (nextcloud - install)

### ISSUE THREAD

**Issue by WarpinWolf** [icewind1991/files_external_dropbox#6] opened 2017-10-17 06:56 UTC
Sorry - but - ran into the issue. Found this discussion: https://github.com/nextcloud/server/issues/991. Comment from Oct. 16 nickvergessen suggests to post issues here - so here we go:
https://github.com/icewind1991/files_external_dropbox Readme says: "Get the app from the app store" - with a link. Following the link leads to the app store with no specific app selected. Searching for dropbox doesn't yield any result. Any suggestions for newbies like me how to get Dropbox integration working again in Nextcloud?

Thanks
Wolf

**Comment by joekerna** [comment] 2017-10-17 09:45
Duplicate of #2

**Closed** 2017-11-09 12:26 UTC
